"ues client"
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Facebook - Connect with friends",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
//         <body className={inter.className}>
//       <SessionWrapper>
//         {children}
//         </SessionWrapper>
//         </body>
//     </html>
//   );
// }

//layout tutorial code
export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
      <Navbar/>
      {children}
      <Footer/>
        </body>
    </html>
  );
}