import { Inter } from "next/font/google";

// import SessionWrapper from "./component/SessionWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Admin : Facebook - Connect with friends",
  description: "Admin Page: Generated by create next app",
};



//layout tutorial code
export default function AdminLayout({ children }) {
  return (
    <>
    <span>Admin NavBar</span>
      {children}
      </>
  );
}